/*
 * Invoices
 * <table><thead><tr><th>Version</th><th>Author</th><th>Date</th><th>Description</th><th>Revision by</th></tr></thead><tbody><tr><td>1.0.0</td><td>Enok</td><td>2022-01-10</td><td>Creates a new invoice (POST)</td><td> - </td></tr></tbody></table>
 *
 * The version of the OpenAPI document: 1;2022-01-10
 * Contact: enok.jesus@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gov.bahamas.invoices.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import gov.bahamas.invoices.model.PreferredContact;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Business object that represents a Client.
 */
@ApiModel(description = "Business object that represents a Client.")
@JsonPropertyOrder({
  Client.JSON_PROPERTY_ID,
  Client.JSON_PROPERTY_NAME,
  Client.JSON_PROPERTY_CODE,
  Client.JSON_PROPERTY_EMAIL,
  Client.JSON_PROPERTY_LANGUAGE,
  Client.JSON_PROPERTY_ADDRESS,
  Client.JSON_PROPERTY_CITY,
  Client.JSON_PROPERTY_POSTAL_CODE,
  Client.JSON_PROPERTY_COUNTRY,
  Client.JSON_PROPERTY_FISCAL_ID,
  Client.JSON_PROPERTY_WEBSITE,
  Client.JSON_PROPERTY_PHONE,
  Client.JSON_PROPERTY_FAX,
  Client.JSON_PROPERTY_PREFERRED_CONTACT,
  Client.JSON_PROPERTY_OBSERVATIONS,
  Client.JSON_PROPERTY_SEND_OPTIONS
})
@JsonTypeName("client")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Client {
  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_LANGUAGE = "language";
  private String language;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private String address;

  public static final String JSON_PROPERTY_CITY = "city";
  private String city;

  public static final String JSON_PROPERTY_POSTAL_CODE = "postal_code";
  private String postalCode;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  private String country;

  public static final String JSON_PROPERTY_FISCAL_ID = "fiscal_id";
  private String fiscalId;

  public static final String JSON_PROPERTY_WEBSITE = "website";
  private String website;

  public static final String JSON_PROPERTY_PHONE = "phone";
  private String phone;

  public static final String JSON_PROPERTY_FAX = "fax";
  private String fax;

  public static final String JSON_PROPERTY_PREFERRED_CONTACT = "preferred_contact";
  private PreferredContact preferredContact;

  public static final String JSON_PROPERTY_OBSERVATIONS = "observations";
  private String observations;

  public static final String JSON_PROPERTY_SEND_OPTIONS = "send_options";
  private Integer sendOptions;


   /**
   * Id auto-generated for a Client
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "41079180", value = "Id auto-generated for a Client")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }




  public Client name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Client name, normally used for a company name.
   * @return name
  **/
  @NotNull
  @ApiModelProperty(example = "Client Name", required = true, value = "Client name, normally used for a company name.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Client code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Client code, your specific code for the client.
   * @return code
  **/
  @NotNull
  @ApiModelProperty(example = "12345", required = true, value = "Client code, your specific code for the client.")
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public Client email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Client email address. Must be a valid email address ex: foo@bar.com
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "foo@bar.com", value = "Client email address. Must be a valid email address ex: foo@bar.com")
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public Client language(String language) {
    
    this.language = language;
    return this;
  }

   /**
   * Client language. May be en, pt or es; defaults to the account language.
   * @return language
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "pt", value = "Client language. May be en, pt or es; defaults to the account language.")
  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLanguage() {
    return language;
  }


  public void setLanguage(String language) {
    this.language = language;
  }


  public Client address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * Client company address.
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Avenida da República, Lisboa", value = "Client company address.")
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress() {
    return address;
  }


  public void setAddress(String address) {
    this.address = address;
  }


  public Client city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * Client’s city.
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lisboa", value = "Client’s city.")
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    this.city = city;
  }


  public Client postalCode(String postalCode) {
    
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Client’s postal code for it’s company address.
   * @return postalCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1050-555", value = "Client’s postal code for it’s company address.")
  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPostalCode() {
    return postalCode;
  }


  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  public Client country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * Country, normally used for a company country. Although country is optional, when supplied, it should match one of the country list on the Appendix of this Documentation.
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Portugal", value = "Country, normally used for a company country. Although country is optional, when supplied, it should match one of the country list on the Appendix of this Documentation.")
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }


  public Client fiscalId(String fiscalId) {
    
    this.fiscalId = fiscalId;
    return this;
  }

   /**
   * The client fiscal ID (Número de Contribuinte).
   * @return fiscalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "508025338", value = "The client fiscal ID (Número de Contribuinte).")
  @JsonProperty(JSON_PROPERTY_FISCAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFiscalId() {
    return fiscalId;
  }


  public void setFiscalId(String fiscalId) {
    this.fiscalId = fiscalId;
  }


  public Client website(String website) {
    
    this.website = website;
    return this;
  }

   /**
   * The client web address.
   * @return website
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "www.invoicexpress.com", value = "The client web address.")
  @JsonProperty(JSON_PROPERTY_WEBSITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWebsite() {
    return website;
  }


  public void setWebsite(String website) {
    this.website = website;
  }


  public Client phone(String phone) {
    
    this.phone = phone;
    return this;
  }

   /**
   * The client phone number.
   * @return phone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "213456789", value = "The client phone number.")
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhone() {
    return phone;
  }


  public void setPhone(String phone) {
    this.phone = phone;
  }


  public Client fax(String fax) {
    
    this.fax = fax;
    return this;
  }

   /**
   * The client fax number.
   * @return fax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "213456788", value = "The client fax number.")
  @JsonProperty(JSON_PROPERTY_FAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFax() {
    return fax;
  }


  public void setFax(String fax) {
    this.fax = fax;
  }


  public Client preferredContact(PreferredContact preferredContact) {
    
    this.preferredContact = preferredContact;
    return this;
  }

   /**
   * Get preferredContact
   * @return preferredContact
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PREFERRED_CONTACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PreferredContact getPreferredContact() {
    return preferredContact;
  }


  public void setPreferredContact(PreferredContact preferredContact) {
    this.preferredContact = preferredContact;
  }


  public Client observations(String observations) {
    
    this.observations = observations;
    return this;
  }

   /**
   * Default observations for the client, the text in here will be added to the observations field of all the invoices sent to this client.
   * @return observations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Observations", value = "Default observations for the client, the text in here will be added to the observations field of all the invoices sent to this client.")
  @JsonProperty(JSON_PROPERTY_OBSERVATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getObservations() {
    return observations;
  }


  public void setObservations(String observations) {
    this.observations = observations;
  }


  public Client sendOptions(Integer sendOptions) {
    
    this.sendOptions = sendOptions;
    return this;
  }

   /**
   * Send options for the client. Available options are: 1 - send only the original document / 2 – the original and duplicate / 3 – the original, duplicate and triplicate. These affect the generated pdf.
   * @return sendOptions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Send options for the client. Available options are: 1 - send only the original document / 2 – the original and duplicate / 3 – the original, duplicate and triplicate. These affect the generated pdf.")
  @JsonProperty(JSON_PROPERTY_SEND_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSendOptions() {
    return sendOptions;
  }


  public void setSendOptions(Integer sendOptions) {
    this.sendOptions = sendOptions;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Client {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    fiscalId: ").append(toIndentedString(fiscalId)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    fax: ").append(toIndentedString(fax)).append("\n");
    sb.append("    preferredContact: ").append(toIndentedString(preferredContact)).append("\n");
    sb.append("    observations: ").append(toIndentedString(observations)).append("\n");
    sb.append("    sendOptions: ").append(toIndentedString(sendOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

