/*
 * Invoices
 * <table><thead><tr><th>Version</th><th>Author</th><th>Date</th><th>Description</th><th>Revision by</th></tr></thead><tbody><tr><td>1.0.0</td><td>Enok</td><td>2022-01-10</td><td>Creates a new invoice (POST)</td><td> - </td></tr></tbody></table>
 *
 * The version of the OpenAPI document: 1;2022-01-10
 * Contact: enok.jesus@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gov.bahamas.invoices.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import gov.bahamas.invoices.model.Invoice;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Business objects that represents a response from Invoice creation.
 */
@ApiModel(description = "Business objects that represents a response from Invoice creation.")
@JsonPropertyOrder({
  InvoicePostRequest.JSON_PROPERTY_INVOICE,
  InvoicePostRequest.JSON_PROPERTY_PROPRIETARY_UID
})
@JsonTypeName("invoicePostRequest")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class InvoicePostRequest {
  public static final String JSON_PROPERTY_INVOICE = "invoice";
  private Invoice invoice;

  public static final String JSON_PROPERTY_PROPRIETARY_UID = "proprietary_uid";
  private String proprietaryUid;


  public InvoicePostRequest invoice(Invoice invoice) {
    
    this.invoice = invoice;
    return this;
  }

   /**
   * Get invoice
   * @return invoice
  **/
  @NotNull
  @Valid
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_INVOICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Invoice getInvoice() {
    return invoice;
  }


  public void setInvoice(Invoice invoice) {
    this.invoice = invoice;
  }


  public InvoicePostRequest proprietaryUid(String proprietaryUid) {
    
    this.proprietaryUid = proprietaryUid;
    return this;
  }

   /**
   * When sending your process&#39; UUID you will prevent the creation of duplicate requests.
   * @return proprietaryUid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "UUID41237123189981ddajkls23478y", value = "When sending your process' UUID you will prevent the creation of duplicate requests.")
  @JsonProperty(JSON_PROPERTY_PROPRIETARY_UID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProprietaryUid() {
    return proprietaryUid;
  }


  public void setProprietaryUid(String proprietaryUid) {
    this.proprietaryUid = proprietaryUid;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoicePostRequest {\n");
    sb.append("    invoice: ").append(toIndentedString(invoice)).append("\n");
    sb.append("    proprietaryUid: ").append(toIndentedString(proprietaryUid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

