/*
 * Invoices
 * <table><thead><tr><th>Version</th><th>Author</th><th>Date</th><th>Description</th><th>Revision by</th></tr></thead><tbody><tr><td>1.0.0</td><td>Enok</td><td>2022-01-10</td><td>Creates a new invoice (POST)</td><td> - </td></tr></tbody></table>
 *
 * The version of the OpenAPI document: 1;2022-01-10
 * Contact: enok.jesus@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gov.bahamas.invoices.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import gov.bahamas.invoices.model.Client;
import gov.bahamas.invoices.model.Item;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Business object that represents an Invoice.
 */
@ApiModel(description = "Business object that represents an Invoice.")
@JsonPropertyOrder({
  Invoice.JSON_PROPERTY_ID,
  Invoice.JSON_PROPERTY_STATUS,
  Invoice.JSON_PROPERTY_ARCHIVED,
  Invoice.JSON_PROPERTY_TYPE,
  Invoice.JSON_PROPERTY_DATE,
  Invoice.JSON_PROPERTY_DUE_DATE,
  Invoice.JSON_PROPERTY_REFERENCE,
  Invoice.JSON_PROPERTY_OBSERVATIONS,
  Invoice.JSON_PROPERTY_RETENTION,
  Invoice.JSON_PROPERTY_PERMALINK,
  Invoice.JSON_PROPERTY_SUM,
  Invoice.JSON_PROPERTY_DISCOUNT,
  Invoice.JSON_PROPERTY_BEFORE_TAXES,
  Invoice.JSON_PROPERTY_TAXES,
  Invoice.JSON_PROPERTY_TOTAL,
  Invoice.JSON_PROPERTY_TAX_EXEMPTION,
  Invoice.JSON_PROPERTY_SEQUENCE_NUMBER,
  Invoice.JSON_PROPERTY_SEQUENCE_ID,
  Invoice.JSON_PROPERTY_MANUAL_SEQUENCE_NUMBER,
  Invoice.JSON_PROPERTY_CLIENT,
  Invoice.JSON_PROPERTY_ITEMS,
  Invoice.JSON_PROPERTY_MB_REFERENCE,
  Invoice.JSON_PROPERTY_OWNER_INVOICE_ID,
  Invoice.JSON_PROPERTY_TAX_EXEMPTION_REASON,
  Invoice.JSON_PROPERTY_CURRENCY_CODE,
  Invoice.JSON_PROPERTY_CURRENCY,
  Invoice.JSON_PROPERTY_RATE
})
@JsonTypeName("invoice")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Invoice {
  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_ARCHIVED = "archived";
  private Boolean archived;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_DATE = "date";
  private LocalDate date;

  public static final String JSON_PROPERTY_DUE_DATE = "due_date";
  private LocalDate dueDate;

  public static final String JSON_PROPERTY_REFERENCE = "reference";
  private String reference;

  public static final String JSON_PROPERTY_OBSERVATIONS = "observations";
  private String observations;

  public static final String JSON_PROPERTY_RETENTION = "retention";
  private Integer retention;

  public static final String JSON_PROPERTY_PERMALINK = "permalink";
  private String permalink;

  public static final String JSON_PROPERTY_SUM = "sum";
  private Double sum;

  public static final String JSON_PROPERTY_DISCOUNT = "discount";
  private Double discount = 0.0d;

  public static final String JSON_PROPERTY_BEFORE_TAXES = "before_taxes";
  private Double beforeTaxes;

  public static final String JSON_PROPERTY_TAXES = "taxes";
  private Double taxes;

  public static final String JSON_PROPERTY_TOTAL = "total";
  private Double total;

  public static final String JSON_PROPERTY_TAX_EXEMPTION = "tax_exemption";
  private String taxExemption;

  public static final String JSON_PROPERTY_SEQUENCE_NUMBER = "sequence_number";
  private String sequenceNumber;

  public static final String JSON_PROPERTY_SEQUENCE_ID = "sequence_id";
  private String sequenceId;

  public static final String JSON_PROPERTY_MANUAL_SEQUENCE_NUMBER = "manual_sequence_number";
  private String manualSequenceNumber;

  public static final String JSON_PROPERTY_CLIENT = "client";
  private Client client;

  public static final String JSON_PROPERTY_ITEMS = "items";
  private List<Item> items = new ArrayList<>();

  public static final String JSON_PROPERTY_MB_REFERENCE = "mb_reference";
  private String mbReference;

  public static final String JSON_PROPERTY_OWNER_INVOICE_ID = "owner_invoice_id";
  private Integer ownerInvoiceId;

  public static final String JSON_PROPERTY_TAX_EXEMPTION_REASON = "tax_exemption_reason";
  private String taxExemptionReason;

  public static final String JSON_PROPERTY_CURRENCY_CODE = "currency_code";
  private String currencyCode;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private String currency;

  public static final String JSON_PROPERTY_RATE = "rate";
  private Double rate;


   /**
   * Id auto-generated for a Client.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "81967052", value = "Id auto-generated for a Client.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }




   /**
   * Represents the Invoice current status.
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "draft", value = "Represents the Invoice current status.")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }




   /**
   * If the Invoice was archived.
   * @return archived
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "If the Invoice was archived.")
  @JsonProperty(JSON_PROPERTY_ARCHIVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getArchived() {
    return archived;
  }




   /**
   * The type of document created.
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Invoice", value = "The type of document created.")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }




  public Invoice date(LocalDate date) {
    
    this.date = date;
    return this;
  }

   /**
   * The invoice date. Must be in format dd/mm/yyyy ex.: 03/12/2015. If format is invalid, date will be set to current date.
   * @return date
  **/
  @NotNull
  @Valid
 @Pattern(regexp="^(3[01]|[12][0-9]|0[1-9])-(1[0-2]|0[1-9])-[0-9]{4}$")  @ApiModelProperty(required = true, value = "The invoice date. Must be in format dd/mm/yyyy ex.: 03/12/2015. If format is invalid, date will be set to current date.")
  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getDate() {
    return date;
  }


  public void setDate(LocalDate date) {
    this.date = date;
  }


  public Invoice dueDate(LocalDate dueDate) {
    
    this.dueDate = dueDate;
    return this;
  }

   /**
   * The invoice due date. Must be in format dd/mm/yyyy ex.: 03/12/2015. If format is invalid, date will be set to current date.
   * @return dueDate
  **/
  @NotNull
  @Valid
 @Pattern(regexp="^(3[01]|[12][0-9]|0[1-9])-(1[0-2]|0[1-9])-[0-9]{4}$")  @ApiModelProperty(required = true, value = "The invoice due date. Must be in format dd/mm/yyyy ex.: 03/12/2015. If format is invalid, date will be set to current date.")
  @JsonProperty(JSON_PROPERTY_DUE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getDueDate() {
    return dueDate;
  }


  public void setDueDate(LocalDate dueDate) {
    this.dueDate = dueDate;
  }


  public Invoice reference(String reference) {
    
    this.reference = reference;
    return this;
  }

   /**
   * The invoice purchase order reference field.
   * @return reference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The invoice purchase order reference field.")
  @JsonProperty(JSON_PROPERTY_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReference() {
    return reference;
  }


  public void setReference(String reference) {
    this.reference = reference;
  }


  public Invoice observations(String observations) {
    
    this.observations = observations;
    return this;
  }

   /**
   * Invoice observations, these will be printed with the invoice.
   * @return observations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Invoice observations, these will be printed with the invoice.")
  @JsonProperty(JSON_PROPERTY_OBSERVATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getObservations() {
    return observations;
  }


  public void setObservations(String observations) {
    this.observations = observations;
  }


  public Invoice retention(Integer retention) {
    
    this.retention = retention;
    return this;
  }

   /**
   * Withholding tax percentage (%). Must be a number between 0 and 99.99.
   * minimum: 0
   * maximum: 99
   * @return retention
  **/
  @javax.annotation.Nullable
 @Min(0) @Max(99)  @ApiModelProperty(value = "Withholding tax percentage (%). Must be a number between 0 and 99.99.")
  @JsonProperty(JSON_PROPERTY_RETENTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRetention() {
    return retention;
  }


  public void setRetention(Integer retention) {
    this.retention = retention;
  }


   /**
   * Permalink.
   * @return permalink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://www.app.invoicexpress.com/documents/81967052fb50a36404eca4a16ead6101a818d87f249de9bf", value = "Permalink.")
  @JsonProperty(JSON_PROPERTY_PERMALINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPermalink() {
    return permalink;
  }




   /**
   * Sum of totals of all itens.
   * @return sum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "500.0", value = "Sum of totals of all itens.")
  @JsonProperty(JSON_PROPERTY_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getSum() {
    return sum;
  }




  public Invoice discount(Double discount) {
    
    this.discount = discount;
    return this;
  }

   /**
   * Sum of discounts of all itens.
   * minimum: 0.0
   * @return discount
  **/
  @javax.annotation.Nullable
 @DecimalMin("0.0")  @ApiModelProperty(example = "0.0", value = "Sum of discounts of all itens.")
  @JsonProperty(JSON_PROPERTY_DISCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getDiscount() {
    return discount;
  }


  public void setDiscount(Double discount) {
    this.discount = discount;
  }


   /**
   * Sum before taxes.
   * @return beforeTaxes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "500.0", value = "Sum before taxes.")
  @JsonProperty(JSON_PROPERTY_BEFORE_TAXES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getBeforeTaxes() {
    return beforeTaxes;
  }




   /**
   * Sum of taxes of all itens.
   * @return taxes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "25.0", value = "Sum of taxes of all itens.")
  @JsonProperty(JSON_PROPERTY_TAXES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTaxes() {
    return taxes;
  }




   /**
   * Total sum with total taxes.
   * @return total
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "525.0", value = "Total sum with total taxes.")
  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTotal() {
    return total;
  }




  public Invoice taxExemption(String taxExemption) {
    
    this.taxExemption = taxExemption;
    return this;
  }

   /**
   * Portuguese IVA exemption code. Required for portuguese accounts on invoices with IVA exempt items (0%). Refer to the Appendix for the complete list of “IVA Exemption Codes”.
   * @return taxExemption
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "M01", value = "Portuguese IVA exemption code. Required for portuguese accounts on invoices with IVA exempt items (0%). Refer to the Appendix for the complete list of “IVA Exemption Codes”.")
  @JsonProperty(JSON_PROPERTY_TAX_EXEMPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTaxExemption() {
    return taxExemption;
  }


  public void setTaxExemption(String taxExemption) {
    this.taxExemption = taxExemption;
  }


   /**
   * Sequence number.
   * @return sequenceNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "6/G", value = "Sequence number.")
  @JsonProperty(JSON_PROPERTY_SEQUENCE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSequenceNumber() {
    return sequenceNumber;
  }




  public Invoice sequenceId(String sequenceId) {
    
    this.sequenceId = sequenceId;
    return this;
  }

   /**
   * Id of the sequence you want to use with this invoice. If missing, the default sequence will be used.
   * @return sequenceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "112233", value = "Id of the sequence you want to use with this invoice. If missing, the default sequence will be used.")
  @JsonProperty(JSON_PROPERTY_SEQUENCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSequenceId() {
    return sequenceId;
  }


  public void setSequenceId(String sequenceId) {
    this.sequenceId = sequenceId;
  }


  public Invoice manualSequenceNumber(String manualSequenceNumber) {
    
    this.manualSequenceNumber = manualSequenceNumber;
    return this;
  }

   /**
   * Required for non portuguese accounts with manual sequence numbering.
   * @return manualSequenceNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Required for non portuguese accounts with manual sequence numbering.")
  @JsonProperty(JSON_PROPERTY_MANUAL_SEQUENCE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getManualSequenceNumber() {
    return manualSequenceNumber;
  }


  public void setManualSequenceNumber(String manualSequenceNumber) {
    this.manualSequenceNumber = manualSequenceNumber;
  }


  public Invoice client(Client client) {
    
    this.client = client;
    return this;
  }

   /**
   * Get client
   * @return client
  **/
  @NotNull
  @Valid
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CLIENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Client getClient() {
    return client;
  }


  public void setClient(Client client) {
    this.client = client;
  }


  public Invoice items(List<Item> items) {
    
    this.items = items;
    return this;
  }

  public Invoice addItemsItem(Item itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * An array of invoice items. If items with the given names do not exist, they are created. If an item already exists, it is updated with the new values. At least one is required.
   * @return items
  **/
  @NotNull
  @Valid
 @Size(min=1)  @ApiModelProperty(required = true, value = "An array of invoice items. If items with the given names do not exist, they are created. If an item already exists, it is updated with the new values. At least one is required.")
  @JsonProperty(JSON_PROPERTY_ITEMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Item> getItems() {
    return items;
  }


  public void setItems(List<Item> items) {
    this.items = items;
  }


  public Invoice mbReference(String mbReference) {
    
    this.mbReference = mbReference;
    return this;
  }

   /**
   * Generates a Multibanco Reference after you finalize your invoice. This option is only available for Portuguese Accounts. You must have the feature enabled on your account first.
   * @return mbReference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "Generates a Multibanco Reference after you finalize your invoice. This option is only available for Portuguese Accounts. You must have the feature enabled on your account first.")
  @JsonProperty(JSON_PROPERTY_MB_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMbReference() {
    return mbReference;
  }


  public void setMbReference(String mbReference) {
    this.mbReference = mbReference;
  }


  public Invoice ownerInvoiceId(Integer ownerInvoiceId) {
    
    this.ownerInvoiceId = ownerInvoiceId;
    return this;
  }

   /**
   * The (owner) invoice associated to this document. This option is only available for credit_notes or debit_notes. You can also send the (owner) guide id when creating an invoice to associate an invoice to a guide.
   * @return ownerInvoiceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "12345", value = "The (owner) invoice associated to this document. This option is only available for credit_notes or debit_notes. You can also send the (owner) guide id when creating an invoice to associate an invoice to a guide.")
  @JsonProperty(JSON_PROPERTY_OWNER_INVOICE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOwnerInvoiceId() {
    return ownerInvoiceId;
  }


  public void setOwnerInvoiceId(Integer ownerInvoiceId) {
    this.ownerInvoiceId = ownerInvoiceId;
  }


  public Invoice taxExemptionReason(String taxExemptionReason) {
    
    this.taxExemptionReason = taxExemptionReason;
    return this;
  }

   /**
   * Used when updating a document and removing all tax exempt items. The code M00 means &#39;Without tax exemption&#39;.
   * @return taxExemptionReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "M00", value = "Used when updating a document and removing all tax exempt items. The code M00 means 'Without tax exemption'.")
  @JsonProperty(JSON_PROPERTY_TAX_EXEMPTION_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTaxExemptionReason() {
    return taxExemptionReason;
  }


  public void setTaxExemptionReason(String taxExemptionReason) {
    this.taxExemptionReason = taxExemptionReason;
  }


  public Invoice currencyCode(String currencyCode) {
    
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * If your plan as multicurrency, you can issue invoices in another currency than your account&#39;s default currency. The currency_code should be one of the following ISO 4217 currency codes.
   * @return currencyCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "BRL", value = "If your plan as multicurrency, you can issue invoices in another currency than your account's default currency. The currency_code should be one of the following ISO 4217 currency codes.")
  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrencyCode() {
    return currencyCode;
  }


  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Brazilian real", value = "")
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrency() {
    return currency;
  }




  public Invoice rate(Double rate) {
    
    this.rate = rate;
    return this;
  }

   /**
   * When sending a currency_code you can specify its&#39; rate.
   * @return rate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1.23565", value = "When sending a currency_code you can specify its' rate.")
  @JsonProperty(JSON_PROPERTY_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getRate() {
    return rate;
  }


  public void setRate(Double rate) {
    this.rate = rate;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o, false, null, true);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Invoice {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    observations: ").append(toIndentedString(observations)).append("\n");
    sb.append("    retention: ").append(toIndentedString(retention)).append("\n");
    sb.append("    permalink: ").append(toIndentedString(permalink)).append("\n");
    sb.append("    sum: ").append(toIndentedString(sum)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    beforeTaxes: ").append(toIndentedString(beforeTaxes)).append("\n");
    sb.append("    taxes: ").append(toIndentedString(taxes)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    taxExemption: ").append(toIndentedString(taxExemption)).append("\n");
    sb.append("    sequenceNumber: ").append(toIndentedString(sequenceNumber)).append("\n");
    sb.append("    sequenceId: ").append(toIndentedString(sequenceId)).append("\n");
    sb.append("    manualSequenceNumber: ").append(toIndentedString(manualSequenceNumber)).append("\n");
    sb.append("    client: ").append(toIndentedString(client)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    mbReference: ").append(toIndentedString(mbReference)).append("\n");
    sb.append("    ownerInvoiceId: ").append(toIndentedString(ownerInvoiceId)).append("\n");
    sb.append("    taxExemptionReason: ").append(toIndentedString(taxExemptionReason)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

