/*
 * Clients
 * <table><thead><tr><th>Version</th><th>Author</th><th>Date</th><th>Description</th><th>Revision by</th></tr></thead><tbody><tr><td>1.0.0</td><td>Enok</td><td>2022-01-09</td><td>Creates a new client (POST)</td><td> - </td></tr></tbody></table>
 *
 * The version of the OpenAPI document: 1;2022-01-09
 * Contact: enok.jesus@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gov.bahamas.clients;

import gov.bahamas.clients.model.ClientPostRequest;
import gov.bahamas.clients.model.ClientPostResponse;
import gov.bahamas.clients.model.ErrorArray;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClientsJsonApi
 */
@Ignore
public class ClientsJsonApiTest {

    private final ClientsJsonApi api = new ClientsJsonApi();

    
    /**
     * Creates a new client.
     *
     * To try it out use api_key: 8b90b198bb858c0e047ee107175c51cd9a3d25a2
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void clientsJsonPostTest() {
        String apiKey = null;
        ClientPostRequest clientPostRequest = null;
        ClientPostResponse response = api.clientsJsonPost(apiKey, clientPostRequest);

        // TODO: test validations
    }
    
}
