/*
 * Invoices
 * <table><thead><tr><th>Version</th><th>Author</th><th>Date</th><th>Description</th><th>Revision by</th></tr></thead><tbody><tr><td>1.0.0</td><td>Enok</td><td>2022-01-10</td><td>Creates a new invoice (POST)</td><td> - </td></tr></tbody></table>
 *
 * The version of the OpenAPI document: 1;2022-01-10
 * Contact: enok.jesus@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gov.bahamas.invoices;

import gov.bahamas.invoices.model.ErrorArray;
import gov.bahamas.invoices.model.InvoicePostRequest;
import gov.bahamas.invoices.model.InvoicePostResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InvoicesJsonApi
 */
@Ignore
public class InvoicesJsonApiTest {

    private final InvoicesJsonApi api = new InvoicesJsonApi();

    
    /**
     * Creates a new invoice.
     *
     * To try it out use api_key: 8b90b198bb858c0e047ee107175c51cd9a3d25a2
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invoicesJsonPostTest() {
        String apiKey = null;
        InvoicePostRequest invoicePostRequest = null;
        InvoicePostResponse response = api.invoicesJsonPost(apiKey, invoicePostRequest);

        // TODO: test validations
    }
    
}
